import React, { ReactNode } from "react";
import "./globals.css";
import Header from "@/components/Header";

interface LayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Bekir App ",
  description: "Generated by create next app",
};
const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default Layout;
